name = "FigureHelpers"
uuid = "9ae22f58-2487-4805-bfc5-386577db46c8"
authors = ["Thomas Wutzler <bgctw@arcor.de>"]
version = "0.1.0"

[deps]
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
FigureHelpersAoGExt = ["Makie", "AlgebraOfGraphics"]
FigureHelpersMakieAbstractMCMCExt = ["Makie", "AbstractMCMC"]
FigureHelpersMakieDistributionsExt = ["Makie", "Distributions"]
FigureHelpersMakieExt = ["Makie", "KernelDensity"]

[compat]
AbstractMCMC = "5.7.2"
AlgebraOfGraphics = "0.9.4, 0.10"
Distributions = "0.25.120"
KernelDensity = "0.6.10"
MCMCChains = "6.0.7, 7"
Makie = "0.21.13"
Parameters = "0.12.3"
StatsBase = "0.34.5"
julia = "1.10"

[workspace]
projects = ["test", "docs"]
